feedie:
    cmd_prefix: null  # disable commands
    bot_owner: [xstill, xstill_]
    shorten_service: null  # v.gd or tinyurl.com
    wrap_url: '<>'

network:
    server: 'chat.freenode.net'
    port: 6667
    password: ''
    bot_nick: 'FEED'
    bot_name: 'feedie pyBot v1.1'
    pubmsg_log: False
    announce_delay: .5
    default_refresh_delay: 35.0
    startup_announces: False

feeds:
    mydealz:
        url: 'https://www.mydealz.de/rss/alle'
        color: 'green'
        channel: '#FEEDs'
        channel_key: ''  # default
        enabled: True    # default
    monsterdealz:
        url: 'http://feeds.feedburner.com/MonsterDealz?format=xml'
        color: 'green'
        channel: '#FEEDs'
    chillmo:
        url: 'http://chillmo.com/feed/'
        color: 'orange'
        channel: '#FEEDs'
    hwluxx:
        url: 'http://www.hardwareluxx.de/index.php/rss/feed/3-hardwareluxx-rss-feed.html'
        color: 'teal'
        channel: '#FEEDs'
    ht4u:
        url: 'http://ht4u.net/feeds/news.xml'
        color: 'purple'
        channel: '#FEEDs'
    pcgames:
        url: 'http://www.pcgames.de/feed.cfm?menu_alias=home'
        color: 'pink'
        channel: '#FEEDs'
    pcgames_hw:
        url: 'http://www.pcgameshardware.de/feed.cfm'
        color: 'red'
        channel: '#FEEDs'
    forum:
        url: 'http://www.forum-raspberrypi.de/syndication2.php?limit=10'
        color: 'red'
        channel: '#Raspberry-Pi'
        refresh_delay: 15.0
